from __future__ import annotations

import typing as t

import sqlalchemy.orm as sa_orm
from flask_sqlalchemy.session import Session

if t.TYPE_CHECKING:
    from .entities import Staff, Branch


@t.runtime_checkable
class BranchRepository(t.Protocol):
    def __init__(self, session: sa_orm.scoped_session[Session]) -> None: ...
    def find_all(self) -> list[Branch]: ...
    def get_by_id(self, branch_id: str) -> Branch | None: ...
    def exists_by_name(self, name: str) -> bool: ...
    def save(self, branch: Branch) -> Branch: ...
    def delete_by_id(self, branch_id: str) -> None: ...


@t.runtime_checkable
class StaffRepository(t.Protocol):
    def __init__(self, session: sa_orm.scoped_session[Session]) -> None: ...
    def find_all(self) -> list[Staff]: ...
    def get_by_id(self, staff_id: str) -> Staff | None: ...
    def exists_by_email(self, email: str) -> bool: ...
    def save(self, staff: Staff) -> Staff: ...
    def delete_by_id(self, staff_id: str) -> None: ...
