from __future__ import annotations

import typing as t

import sqlalchemy.orm as sa_orm
from flask_sqlalchemy.session import Session

from lms.domain.catalogs.entities import Copy

if t.TYPE_CHECKING:
    from .entities import Hold, Loan


@t.runtime_checkable
class LoanRepository(t.Protocol):
    def __init__(self, session: sa_orm.scoped_session[Session]) -> None: ...
    def find_all(self) -> list[Loan]: ...
    def find_by_patron_id(self, patron_id: str) -> list[Loan]: ...
    def get_by_id(self, loan_id: str) -> Loan | None: ...
    def save(self, loan: Loan, copy: Copy) -> Loan: ...
    def delete_by_id(self, loan_id: str) -> None: ...


@t.runtime_checkable
class HoldRepository(t.Protocol):
    def __init__(self, session: sa_orm.scoped_session[Session]) -> None: ...
    def find_all(self) -> list[Hold]: ...
    def find_active_holds_by_patron(self, patron_id: str) -> list[Hold]: ...
    def find_active_holds_by_item(self, item_id: str) -> list[Hold]: ...
    def get_by_id(self, hold_id: str) -> Hold | None: ...
    def save(self, hold: Hold) -> Hold: ...
    def delete_by_id(self, hold_id: str) -> None: ...
