from __future__ import annotations

import typing as t

import sqlalchemy.orm as sa_orm
from flask_sqlalchemy.session import Session

if t.TYPE_CHECKING:
    from .entities import Vendor, AcquisitionOrder, AcquisitionOrderLine


@t.runtime_checkable
class AcquisitionOrderRepository(t.Protocol):
    def __init__(self, session: sa_orm.scoped_session[Session]) -> None: ...
    def find_all(self) -> list[AcquisitionOrder]: ...
    def get_by_id(self, order_id: str) -> AcquisitionOrder | None: ...
    def save(self, order: AcquisitionOrder) -> AcquisitionOrder: ...


@t.runtime_checkable
class AcquisitionOrderLineRepository(t.Protocol):
    def __init__(self, session: sa_orm.scoped_session[Session]) -> None: ...
    def find_by_order(self, order_id: str) -> list[AcquisitionOrderLine]: ...
    def get_by_id(self, order_line_id: str) -> AcquisitionOrderLine | None: ...


@t.runtime_checkable
class VendorRepository(t.Protocol):
    def __init__(self, session: sa_orm.scoped_session[Session]) -> None: ...
    def find_all(self) -> list[Vendor]: ...
    def get_by_id(self, vendor_id: str) -> Vendor | None: ...
    def save(self, vendor: Vendor) -> Vendor: ...
