from __future__ import annotations

import typing as t

import sqlalchemy.orm as sa_orm
from flask_sqlalchemy.session import Session

if t.TYPE_CHECKING:
    from .entities import Fine, Patron


@t.runtime_checkable
class PatronRepository(t.Protocol):
    def __init__(self, session: sa_orm.scoped_session[Session]) -> None: ...
    def find_all(self) -> list[Patron]: ...
    def get_by_id(self, patron_id: str) -> Patron | None: ...
    def exists_by_email(self, email: str) -> bool: ...
    def save(self, patron: Patron) -> Patron: ...
    def delete_by_id(self, patron_id: str) -> None: ...


@t.runtime_checkable
class FineRepository(t.Protocol):
    def __init__(self, session: sa_orm.scoped_session[Session]) -> None: ...
    def find_all(self) -> list[Fine]: ...
    def get_by_id(self, fine_id: str) -> Fine | None: ...
    def save(self, fine: Fine) -> Fine: ...
    def delete_by_id(self, fine_id: str) -> None: ...
