from __future__ import annotations

import typing as t

import sqlalchemy.orm as sa_orm
from flask_sqlalchemy.session import Session

if t.TYPE_CHECKING:
    from .entities import Serial, Serials, SerialIssue, SerialIssues


@t.runtime_checkable
class SerialRepository(t.Protocol):
    def __init__(self, session: sa_orm.scoped_session[Session]) -> None: ...
    def find_all(self) -> Serials: ...
    def get_by_id(self, serial_id: str) -> Serial | None: ...
    def save(self, serial: Serial) -> Serial: ...
    def delete_by_id(self, serial_id: str) -> None: ...


@t.runtime_checkable
class SerialIssueRepository(t.Protocol):
    def __init__(self, session: sa_orm.scoped_session[Session]) -> None: ...
    def find_all(self) -> SerialIssues: ...
    def get_by_id(self, issue_id: str) -> SerialIssue | None: ...
    def save(self, issue: SerialIssue) -> SerialIssue: ...
    def delete_by_id(self, issue_id: str) -> None: ...
