from __future__ import annotations

import typing as t

import sqlalchemy.orm as sa_orm
from flask_sqlalchemy.session import Session

if t.TYPE_CHECKING:
    from .entities import Copy, Item, Author, Category, Publisher


@t.runtime_checkable
class CopyRepository(t.Protocol):
    def __init__(self, session: sa_orm.scoped_session[Session]) -> None: ...
    def find_all(self) -> list[Copy]: ...
    def get_by_id(self, copy_id: str) -> Copy | None: ...
    def save(self, copy: Copy) -> Copy: ...
    def delete_by_id(self, copy_id: str) -> None: ...


@t.runtime_checkable
class ItemRepository(t.Protocol):
    def __init__(self, session: sa_orm.scoped_session[Session]) -> None: ...
    def find_all(self) -> list[Item]: ...
    def get_by_id(self, item_id: str) -> Item | None: ...
    def exists_by_title(self, title: str) -> bool: ...
    def save(self, item: Item) -> Item: ...
    def delete_by_id(self, item_id: str) -> None: ...


@t.runtime_checkable
class CategoryRepository(t.Protocol):
    def find_all(self) -> list[Category]: ...
    def get_by_id(self, category_id: str) -> Category | None: ...
    def save(self, category: Category) -> Category: ...
    def delete_by_id(self, category_id: str) -> None: ...


@t.runtime_checkable
class AuthorRepository(t.Protocol):
    def find_all(self) -> list[Author]: ...
    def get_by_id(self, author_id: str) -> Author | None: ...
    def save(self, author: Author) -> Author: ...
    def delete_by_id(self, author_id: str) -> None: ...


@t.runtime_checkable
class PublisherRepository(t.Protocol):
    def find_all(self) -> list[Publisher]: ...
    def get_by_id(self, publisher_id: str) -> Publisher | None: ...
    def save(self, publisher: Publisher) -> Publisher: ...
    def delete_by_id(self, publisher_id: str) -> None: ...
